# Generated by Django 5.1.1 on 2025-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroPacientes', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
