# Generated by Django 5.1.1 on 2025-02-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroPacientes', '0004_cita_atendido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpaciente',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='historialpaciente',
            name='atendido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialpaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='RegistroPacientes.paciente'),
        ),
    ]
